# Generated by Django 3.1.3 on 2020-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201118_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_num',
            field=models.IntegerField(),
        ),
    ]
