# Generated by Django 3.1.3 on 2020-11-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201118_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pages_num', models.IntegerField()),
                ('cover_image', models.CharField(max_length=50)),
                ('author', models.ManyToManyField(through='books.WrittenBy', to='books.AuthorT')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='bookt',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.publishert'),
        ),
        migrations.AlterField(
            model_name='writtenby',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.authort'),
        ),
        migrations.AlterField(
            model_name='writtenby',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.bookt'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
