# Generated by Django 3.1.4 on 2021-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210110_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_deadend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
