# Generated by Django 3.1.5 on 2021-01-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0002_course_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
