# Generated by Django 3.1.5 on 2021-01-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2m_app', '0004_auto_20210111_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
